// app/terms/page.tsx
import { H1, H2, H3, P } from "@/components/ui/typography";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "Read our comprehensive terms of service",
};

export default function TermsPage() {
  return (
    <div className="mt-5 max-w-6xl mx-auto px-4 py-8">
      <H1>Terms of Service</H1>
      <P className="text-muted-foreground">Last Updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</P>
      
      <section className="mt-8">
        <H2>1. Introduction</H2>
        <P>
          Welcome to our financial reporting application ("the App"). These Terms of Service ("Terms") govern your access to and use of our App and services. By accessing or using the App, you agree to be bound by these Terms and our Privacy Policy.
        </P>
        <P>
          The App is designed for educational purposes to help users understand financial reporting and analysis. It generates financial reports based on input data, but does not provide financial advice or guarantee investment returns.
        </P>
      </section>

      <section className="mt-8">
        <H2>2. Educational Purpose Disclaimer</H2>
        <P>
          The App is intended solely for educational and informational purposes. All financial reports generated by the App should not be construed as professional financial advice, investment recommendations, or guarantees of future performance.
        </P>
        <P>
          The App demonstrates financial concepts and reporting techniques, but actual financial outcomes may vary significantly based on numerous factors beyond the App's control or predictive capabilities.
        </P>
      </section>

      <section className="mt-8">
        <H2>3. No Investment Guarantees</H2>
        <P>
          The App does not guarantee any specific return on investment (ROI) or financial outcome. Past performance, whether actual or simulated through the App, is not indicative of future results.
        </P>
        <P>
          All investments involve risk, and you should consult with a qualified financial advisor before making any investment decisions. You acknowledge that any use of the App's outputs for actual investment purposes is at your own risk.
        </P>
      </section>

      <section className="mt-8">
        <H2>4. GDPR Compliance</H2>
        <P>
          We are fully committed to complying with the General Data Protection Regulation (GDPR). Our data collection, processing, and storage practices are designed to protect your privacy and personal data.
        </P>
        <H3>4.1 Data Collection</H3>
        <P>
          We collect only the data necessary to provide our services. This may include personal data you voluntarily provide and usage data about how you interact with the App.
        </P>
        <H3>4.2 Your Rights</H3>
        <P>
          Under GDPR, you have the right to access, rectify, erase, restrict processing of, and receive a portable copy of your personal data. You may also object to certain processing activities.
        </P>
        <H3>4.3 Data Security</H3>
        <P>
          We implement appropriate technical and organizational measures to ensure a level of security appropriate to the risk, including encryption, access controls, and regular security assessments.
        </P>
      </section>

      <section className="mt-8">
        <H2>5. User Responsibilities</H2>
        <P>
          You agree to use the App only for lawful purposes and in accordance with these Terms. You are responsible for:
        </P>
        <ul className="list-disc pl-6 space-y-2 mt-2">
          <li>Providing accurate information when using the App</li>
          <li>Maintaining the confidentiality of your account credentials</li>
          <li>All activities that occur under your account</li>
          <li>Complying with all applicable laws and regulations</li>
        </ul>
      </section>

      <section className="mt-8">
        <H2>6. Intellectual Property</H2>
        <P>
          The App and its entire contents, features, and functionality (including all reports, templates, and algorithms) are owned by us and are protected by international copyright and intellectual property laws.
        </P>
        <P>
          You are granted a limited, non-exclusive license to use the App for its intended educational purposes. You may not reproduce, distribute, modify, or create derivative works without our express permission.
        </P>
      </section>

      <section className="mt-8">
        <H2>7. Limitation of Liability</H2>
        <P>
          To the maximum extent permitted by law, we shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues resulting from:
        </P>
        <ul className="list-disc pl-6 space-y-2 mt-2">
          <li>Your use or inability to use the App</li>
          <li>Any financial decisions made based on the App's outputs</li>
          <li>Any unauthorized access to or use of our servers and/or any personal information stored therein</li>
          <li>Any errors or omissions in any content or for any loss or damage incurred as a result of the use of any content posted or otherwise made available through the App</li>
        </ul>
      </section>

      <section className="mt-8">
        <H2>8. Modifications to Terms</H2>
        <P>
          We reserve the right to modify these Terms at any time. We will provide notice of any material changes through the App or via email. Your continued use of the App after such modifications constitutes your acceptance of the new Terms.
        </P>
      </section>

      <section className="mt-8">
        <H2>9. Governing Law</H2>
        <P>
          These Terms shall be governed by and construed in accordance with the laws of [Your Country/Jurisdiction], without regard to its conflict of law provisions.
        </P>
      </section>

      <section className="mt-8">
        <H2>10. Contact Information</H2>
        <P>
          For any questions about these Terms or the App, please contact us at:
        </P>
        <P className="mt-2 font-medium">
          contact@FinanceReport.com<br />
          Financial Reporting Company<br />
          123 Main Street, City, State, Country
        </P>
      </section>
    </div>
  );
}
